-- Generated from: madagascar-analyzer-test-data.xml
-- DO NOT EDIT - This file is auto-generated from DBUnit XML
-- Generated by: xml-to-sql.py

SET search_path TO clinlims;

INSERT INTO analyzer (id, name, analyzer_type, DESCRIPTION, identifier_pattern, is_active, ip_address, port, protocol_version, status, last_updated) VALUES (2006, 'Mindray BA-88A', 'CHEMISTRY', 'ASTM over RS232 Serial', 'MINDRAY.*BA-88A|BA88A', FALSE, '172.20.1.100', 9600, 'ASTM_LIS2_A2', 'ACTIVE', '2026-02-02 00:00:00') ON CONFLICT DO NOTHING;
INSERT INTO analyzer (id, name, analyzer_type, DESCRIPTION, identifier_pattern, is_active, ip_address, port, protocol_version, status, last_updated) VALUES (2007, 'Mindray BC-5380', 'HEMATOLOGY', 'HL7 v2.3.1 over TCP/IP (MLLP)', 'MINDRAY.*BC.?5380|BC5380', FALSE, '172.20.1.101', 5562, 'HL7_V2_3_1', 'ACTIVE', '2026-02-02 00:00:00') ON CONFLICT DO NOTHING;
INSERT INTO analyzer (id, name, analyzer_type, DESCRIPTION, identifier_pattern, is_active, ip_address, port, protocol_version, status, last_updated) VALUES (2008, 'Mindray BS-360E', 'CHEMISTRY', 'HL7 v2.3.1 over TCP/IP (MLLP)', 'MINDRAY.*BS.?360E|BS360E', FALSE, '172.20.1.102', 5563, 'HL7_V2_3_1', 'ACTIVE', '2026-02-02 00:00:00') ON CONFLICT DO NOTHING;
INSERT INTO analyzer (id, name, analyzer_type, DESCRIPTION, identifier_pattern, is_active, ip_address, port, protocol_version, status, last_updated) VALUES (2012, 'Mindray BC2000', 'HEMATOLOGY', 'HL7 v2.3.1 over TCP/IP (MLLP)', 'MINDRAY.*BC.?2000', FALSE, '172.20.1.103', 5564, 'HL7_V2_3_1', 'ACTIVE', '2026-02-02 00:00:00') ON CONFLICT DO NOTHING;

-- Update sequences to avoid ID conflicts after fixture data
SELECT setval('analyzer_seq', 2012, true);
